export const flipStyles = {
  page: 'relative isolate flex flex-col gap-4 p-4 max-w-2xl mx-auto w-full',
  // day -> night gradient accent
  banner: {
    base: 'flip-now-banner rounded-xl border-2 p-4 shadow-md',
    day: 'bg-gradient-to-br from-amber-50 to-orange-50 border-amber-400 text-amber-950',
    night: 'bg-gradient-to-br from-indigo-950 to-slate-900 border-indigo-400 text-indigo-50',
    eyebrow: 'font-mono text-xs uppercase tracking-widest opacity-70',
    label: 'text-xl font-semibold mt-1',
    action: 'mt-2 text-base leading-snug',
    overrideRow: 'mt-4 flex flex-wrap gap-2',
  },
  timers: {
    grid: 'grid grid-cols-2 sm:grid-cols-3 gap-3',
    card: 'flip-timer-card rounded-lg border border-gray-200 bg-white p-3 shadow-sm',
    label: 'text-xs text-gray-500',
    value: 'font-mono text-2xl mt-1 tabular-nums',
    ok: 'text-emerald-600',
    warn: 'text-amber-600',
    over: 'text-red-600',
    sub: 'text-xs text-gray-400 mt-1',
  },
  rules: {
    wrap: 'flex flex-wrap gap-2',
    chip: 'flip-rule-chip inline-flex items-center gap-1 rounded-full border px-3 py-1 text-xs font-medium cursor-pointer bg-gray-50 border-gray-300 text-gray-700 hover:bg-gray-100',
    chipOpen: 'bg-teal-50 border-teal-400 text-teal-800',
    why: 'flip-rule-why mt-2 rounded-md bg-gray-50 border border-gray-200 p-3 text-sm text-gray-700',
  },
  escalation: {
    banner: 'rounded-lg border-2 border-red-400 bg-red-50 p-3 text-sm text-red-800 font-medium',
    reference: 'flip-escalation-reference text-xs text-gray-500 mt-2',
    disclaimer: 'flip-disclaimer text-center text-xs text-gray-400 py-4',
  },
  nudge: 'flip-nudge rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900',
  section: 'flex flex-col gap-2',
  sectionTitle: 'flip-section-title text-sm font-semibold text-gray-600',
  wizard: {
    panel: 'flip-wizard-panel rounded-xl border-2 border-teal-300 bg-white p-4 shadow-md',
    header: 'flex items-center justify-between mb-2',
    title: 'flip-wizard-title text-sm font-semibold text-teal-800',
    prompt: 'text-base font-medium',
    help: 'text-xs text-gray-500 mt-1',
    options: 'mt-3 flex flex-col gap-2',
    option: 'flip-wizard-option text-left rounded-lg border border-gray-300 bg-gray-50 px-3 py-2.5 text-sm hover:border-teal-400 hover:bg-teal-50 cursor-pointer',
    outcomeTitle: 'text-base font-semibold',
    actions: 'list-disc ml-5 mt-2 space-y-1 text-sm',
    timing: 'mt-3 rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900',
    why: 'flip-wizard-why mt-3 text-sm text-gray-600',
    ruleRow: 'mt-2 flex gap-1.5',
    ruleChip: 'flip-wizard-rulechip font-mono text-[10px] rounded bg-gray-100 border border-gray-300 px-1.5 py-0.5 text-gray-600',
    entryGrid: 'grid grid-cols-1 sm:grid-cols-2 gap-2',
    entryBtn: 'flip-wizard-entry text-left rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm font-medium hover:border-teal-400 hover:bg-teal-50 cursor-pointer',
  },
  toggle: {
    row: 'flex gap-1 rounded-full border border-gray-300 bg-gray-100 p-1 w-fit',
    btn: 'flip-toggle-btn rounded-full px-4 py-1.5 text-sm font-medium text-gray-600 cursor-pointer',
    btnActive: 'bg-white text-teal-700 shadow-sm border border-teal-300',
  },
} as const;
